name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: clean
      run: xcodebuild clean  -scheme TVBox | xcpretty
    - name: Run tests
      run: sxcodebuild test -scheme TVBox -destination 'platform=iOS Simulator,name=iPhone 11 Pro,OS=13.4' | xcpretty -s
